version: "3.9"

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${UPSTASH_REDIS_REST_URL}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: auth-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: